apiVersion: v1
kind: Service
metadata:
  name: vulnerability-detector
  namespace: autofix
  labels:
    app: vulnerability-detector
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  selector:
    app: vulnerability-detector
