apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autofix-bot-rolebinding
  namespace: autofix-bot
subjects:
- kind: ServiceAccount
  name: autofix-bot
  namespace: autofix-bot
roleRef:
  kind: Role
  name: autofix-bot-role
  apiGroup: rbac.authorization.k8s.io
