apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: contracts-service-pdb
  labels:
    app: contracts-service
    namespace.io/team: contracts-team
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: contracts-service
  
  # 替代方案：使用 maxUnavailable
  # maxUnavailable: 1
